// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var React = require("react");
var ReactTestingLibrary = require("bs-react-testing-library/src/ReactTestingLibrary.bs.js");

Jest.test("Component renders", (function (param) {
        var eta = React.createElement("div", {
              style: {
                color: "rebeccapurple"
              }
            }, React.createElement("h1", undefined, "Heading"));
        var result = ReactTestingLibrary.render(undefined, undefined, eta);
        var element = ReactTestingLibrary.getByText(/* `Str */[
              4153489,
              "Heading"
            ], undefined, result);
        return Jest.Expect[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](element));
      }));

/*  Not a pure module */
