// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var spacing = /* array */[
  4,
  8,
  12,
  16,
  24,
  32,
  48,
  72
];

function calculate(main, axis, individual) {
  if (individual !== undefined) {
    return individual;
  } else if (axis !== undefined) {
    return axis;
  } else if (main !== undefined) {
    return main;
  } else {
    return /* zero */-789508312;
  }
}

function convert(x) {
  if (typeof x === "number" || x[0] !== 25744) {
    return x;
  } else {
    var v = x[1];
    return Belt_Option.mapWithDefault(Belt_Array.get(spacing, v), /* `px */[
                25096,
                v
              ], (function (x) {
                  return /* `px */[
                          25096,
                          x
                        ];
                }));
  }
}

function convertMargin(a) {
  if (typeof a === "number" || a[0] !== 25744) {
    return a;
  } else {
    var v = a[1];
    return Belt_Option.mapWithDefault(Belt_Array.get(spacing, v), /* `px */[
                25096,
                v
              ], (function (x) {
                  return /* `px */[
                          25096,
                          x
                        ];
                }));
  }
}

function make(p, pt, pr, pb, pl, px, py) {
  return /* record */[
          /* top */convert(calculate(p, py, pt)),
          /* bottom */convert(calculate(p, py, pb)),
          /* left */convert(calculate(p, px, pl)),
          /* right */convert(calculate(p, px, pr))
        ];
}

function makeMargin(p, pt, pr, pb, pl, px, py) {
  return /* record */[
          /* top */convertMargin(calculate(p, py, pt)),
          /* bottom */convertMargin(calculate(p, py, pb)),
          /* left */convertMargin(calculate(p, px, pl)),
          /* right */convertMargin(calculate(p, px, pr))
        ];
}

var System = /* module */[
  /* calculate */calculate,
  /* convert */convert,
  /* convertMargin */convertMargin,
  /* make */make,
  /* makeMargin */makeMargin
];

var Theme = /* module */[
  /* spacing */spacing,
  /* System */System
];

function Box(Props) {
  var p = Props.p;
  var pt = Props.pt;
  var pr = Props.pr;
  var pb = Props.pb;
  var pl = Props.pl;
  var px = Props.px;
  var py = Props.py;
  var children = Props.children;
  var scaleValue = make(p, pt, pr, pb, pl, px, py);
  var createPadding = function (raw) {
    return Css.style(/* :: */[
                Css.paddingTop(raw[/* top */0]),
                /* :: */[
                  Css.paddingRight(raw[/* right */3]),
                  /* :: */[
                    Css.paddingLeft(raw[/* left */2]),
                    /* :: */[
                      Css.paddingBottom(raw[/* bottom */1]),
                      /* [] */0
                    ]
                  ]
                ]
              ]);
  };
  createPadding(scaleValue);
  return React.createElement("div", {
              className: Css.style(/* :: */[
                    Css.padding(scaleValue[/* top */0]),
                    /* [] */0
                  ])
            }, children);
}

var make$1 = Box;

exports.Theme = Theme;
exports.make = make$1;
/* Css Not a pure module */
