// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var spacing = /* array */[
  4,
  8,
  12,
  16,
  24,
  32,
  48,
  72
];

function calculate(main, axis, individual) {
  if (individual !== undefined) {
    return individual;
  } else if (axis !== undefined) {
    return axis;
  } else if (main !== undefined) {
    return main;
  } else {
    return /* zero */-789508312;
  }
}

function make(p, pt, pr, pb, pl, px, py) {
  var value = calculate(p, py, pt);
  if (typeof value === "number" || value[0] !== 25744) {
    return value;
  } else {
    var v = value[1];
    return Belt_Option.mapWithDefault(Belt_Array.get(spacing, v), /* `px */[
                25096,
                v
              ], (function (x) {
                  return /* `px */[
                          25096,
                          x
                        ];
                }));
  }
}

var System = /* module */[
  /* calculate */calculate,
  /* make */make
];

var Theme = /* module */[
  /* spacing */spacing,
  /* System */System
];

function Box(Props) {
  var p = Props.p;
  var pt = Props.pt;
  var pr = Props.pr;
  var pb = Props.pb;
  var pl = Props.pl;
  var px = Props.px;
  var py = Props.py;
  var children = Props.children;
  var scaleValue = make(p, pt, pr, pb, pl, px, py);
  return React.createElement("div", {
              className: Css.style(/* :: */[
                    Css.padding(scaleValue),
                    /* [] */0
                  ])
            }, children);
}

var make$1 = Box;

exports.Theme = Theme;
exports.make = make$1;
/* Css Not a pure module */
