// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

function Box(Props) {
  Props.p;
  var children = Props.children;
  return React.createElement("div", {
              className: Css.style(/* :: */[
                    Css.padding(Css.px(10)),
                    /* [] */0
                  ])
            }, children);
}

var make = Box;

exports.make = make;
/* Css Not a pure module */
